issuer: http://dex:5556/

storage:
  type: postgres
  config:
    host: postgres
    database: dex
    user: dex
    password: dex
    ssl:
      mode: disable

enablePasswordDB: true

web:
  http: 0.0.0.0:5556

telemetry: 
  http: 0.0.0.0:5558

oauth2:
  skipApprovalScreen: true
  passwordConnector: ldap

logger:
  level: "debug"
  format: "json"

connectors:
- type: ldap
  name: OpenLDAP
  id: ldap
  config:
    host: ldap:1389
    insecureNoSSL: true
    secureSkipVerify: false
    bindDN: cn=admin,dc=example,dc=com
    bindPW: admin
    usernamePrompt: Email Address

    userSearch: 
      baseDN: ou=users,dc=example,dc=com
      filter: "(objectClass=person)"
      username: mail
      idAttr: entryUUID
      emailtAttr: mail
      nameAttr: sn

    groupSearch:
      baseDN: ou=groups,dc=example,dc=com
      filter: "(objectClass=groupOfNames)"
      userMatchers:
      - userAttr: DN
        groupAttr: member
      nameAttr: cn

staticClients:
- id: main-application
  name: 'MainApp'
  secret: rojUkzzGdg6u3RsMzxZykbMcai8jIsen
  public: false